blank_issues_enabled: false
contact_links:
  - name: The program won't run/can't install
    url: https://github.com/seanpm2001/SNU_2D_ProgrammingTools/tree/master/Docs/Installation/
    about: This question will be ignored if asked. Please read the docs.
  - name: I want to help develop
    url: https://github.com/seanpm2001/Teams/discussions/
    about: Thank you for your interest in this project! Please consider joining a team to start developing with me
# name: Untitled
# url: https://example.com/
# about: blank
# name: Untitled 2
# url: https://example.com/
# about: blank
# name: Untitled 3
# url: https://example.com/
# about: blank

# File info
# File version: 2 (2022, Wednesday, May 18th at 3:39 pm PST)
# File type: GitHub issue template config file (*.yml)
# Line count (including blank lines and compiler line): 23
