name: Raku MacOS Star Test

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:

    - uses: actions/checkout@v2

    - name: Install Raku
      run: brew install rakudo-star

    - name: Raku version
      run: raku -v

    - name: Install Module dependencies
      run: zef install --deps-only .

    - name: Run tests
      run: zef test --verbose .
